/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_SAFER-FFI-TOKENIZERS__
#define __RUST_SAFER-FFI-TOKENIZERS__

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FFITokenizer FFITokenizer_t;

FFITokenizer_t * tokenizer_new (void);

void tokenizer_encode (
    FFITokenizer_t const * it);

void tokenizer_drop (
    FFITokenizer_t * ptr);


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct {

    int64_t * ptr;

    size_t len;

    size_t cap;

} Vec_int64_t;

typedef struct {

    Vec_int64_t ids;

    Vec_int64_t type_ids;

    Vec_int64_t words;

} FFIEncoding_t;

void encoding_drop (
    FFIEncoding_t * ptr);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_SAFER-FFI-TOKENIZERS__ */
